services:
  app:
    build:
      context: .
      dockerfile: Authentication/Dockerfile
    container_name: vifinancenews_app
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - search_service
      - summariser_service
    networks:
      - vifinancenet

  search_service:
    build:
      context: .
      dockerfile: SearchService/Dockerfile
    container_name: search_service
    ports:
      - "5001:5000"
    env_file:
      - .env
    networks:
      - vifinancenet

  summariser_service:
    build:
      context: .
      dockerfile: SummariserService/Dockerfile
    container_name: summariser_service
    ports:
      - "5002:5000"
    env_file:
      - .env
    networks:
      - vifinancenet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vifinancenews_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    networks:
      - vifinancenet

  redis:
    image: redis
    container_name: vifinancenews_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - vifinancenet

networks:
  vifinancenet:
    driver: bridge