apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
        - name: analysis-service
          build:
            context: .
            dockerfile: AnalysisService/Dockerfile
          ports:
            - containerPort: 7003
          envFrom:
            - configMapRef:
                name: vifinancenews-config
            - secretRef:
                name: vifinancenews-secret